##
## intsurv: Integrative Survival Models
## Copyright (C) 2017-2019  Wenjie Wang <wjwang.stat@gmail.com>
##
## This file is part of the R package intsurv.
##
## The R package intsurv is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package intsurv is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coxph_cure <- function(time, event, cox_x, cure_x, cure_intercept = TRUE, cox_start = 0L, cure_start = 0L, em_max_iter = 1000L, em_rel_tol = 1e-3, cox_mstep_max_iter = 30L, cox_mstep_rel_tol = 1e-3, cure_mstep_max_iter = 30L, cure_mstep_rel_tol = 1e-6) {
    .Call('_intsurv_coxph_cure', PACKAGE = 'intsurv', time, event, cox_x, cure_x, cure_intercept, cox_start, cure_start, em_max_iter, em_rel_tol, cox_mstep_max_iter, cox_mstep_rel_tol, cure_mstep_max_iter, cure_mstep_rel_tol)
}

coxph_cure_reg <- function(time, event, cox_x, cure_x, cure_intercept = TRUE, cox_lambda = 0L, cox_nlambda = 1L, cox_lambda_min_ratio = 1e-4, cox_penalty_factor = 0L, cure_lambda = 0L, cure_nlambda = 1L, cure_lambda_min_ratio = 1e-4, cure_penalty_factor = 0L, cox_start = 0L, cure_start = 0L, em_max_iter = 200L, em_rel_tol = 1e-4, cox_mstep_max_iter = 10L, cox_mstep_rel_tol = 1e-2, cure_mstep_max_iter = 10L, cure_mstep_rel_tol = 1e-2) {
    .Call('_intsurv_coxph_cure_reg', PACKAGE = 'intsurv', time, event, cox_x, cure_x, cure_intercept, cox_lambda, cox_nlambda, cox_lambda_min_ratio, cox_penalty_factor, cure_lambda, cure_nlambda, cure_lambda_min_ratio, cure_penalty_factor, cox_start, cure_start, em_max_iter, em_rel_tol, cox_mstep_max_iter, cox_mstep_rel_tol, cure_mstep_max_iter, cure_mstep_rel_tol)
}

aggregateSum <- function(x, indices, simplify = TRUE, cumulative = FALSE, reversely = FALSE) {
    .Call('_intsurv_aggregateSum', PACKAGE = 'intsurv', x, indices, simplify, cumulative, reversely)
}

revcumsum <- function(x) {
    .Call('_intsurv_revcumsum', PACKAGE = 'intsurv', x)
}

int_coxph_cure <- function(time, event, cox_x, cure_x, cure_intercept = TRUE, cox_start = 0L, cure_start = 0L, prob_event_start = 0.5, em_max_iter = 1000L, em_rel_tol = 1e-3, cox_mstep_max_iter = 30L, cox_mstep_rel_tol = 1e-3, cure_mstep_max_iter = 30L, cure_mstep_rel_tol = 1e-6) {
    .Call('_intsurv_int_coxph_cure', PACKAGE = 'intsurv', time, event, cox_x, cure_x, cure_intercept, cox_start, cure_start, prob_event_start, em_max_iter, em_rel_tol, cox_mstep_max_iter, cox_mstep_rel_tol, cure_mstep_max_iter, cure_mstep_rel_tol)
}

