##
## intsurv: Integrative Survival Models
## Copyright (C) 2017-2018  Wenjie Wang <wjwang.stat@gmail.com>
##
## This file is part of the R package intsurv.
##
## The R package intsurv is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package intsurv is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregateSum <- function(x, indices, simplify = TRUE, cumulate = FALSE, revcum = FALSE) {
    .Call('_intsurv_aggregateSum', PACKAGE = 'intsurv', x, indices, simplify, cumulate, revcum)
}

revcumsum <- function(x) {
    .Call('_intsurv_revcumsum', PACKAGE = 'intsurv', x)
}

